# Generated by Django 4.2.30 on 2026-06-06 11:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code Postal')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('prospect', 'Prospect'), ('vip', 'VIP')], default='actif', max_length=20, verbose_name='Statut')),
                ('categorie', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise'), ('association', 'Association'), ('administration', 'Administration')], default='particulier', max_length=20, verbose_name='Catégorie')),
                ('entreprise', models.CharField(blank=True, max_length=200, null=True, verbose_name='Entreprise')),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Chiffre d'affaires (€)")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_interaction', models.CharField(choices=[('appel', 'Appel téléphonique'), ('email', 'Email'), ('reunion', 'Réunion'), ('visite', 'Visite'), ('autre', 'Autre')], default='appel', max_length=20, verbose_name='Type')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('utilisateur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Utilisateur')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'ordering': ['-date'],
            },
        ),
    ]
